### ISSUE TITLE
Docs: Feedback for Start a Cluster of Redpanda Brokers with Redpanda Console in Docker (version stuff broken)

### ISSUE THREAD

**Issue by jason-da-redpanda** [redpanda-data/redpanda-labs#48]
Placeholder stuff magic seems busted 

v${REDPANDA_VERSION:?Set a Redpanda version}
 v${REDPANDA_CONSOLE_VERSION:?Set a Redpanda Console version}

**Comment by JakeSCahill** [comment]
Fixed in https://github.com/redpanda-data/docs-extensions-and-macros/pull/61
